server:
  port: 8082

spring:
  application:
    name: Employee-Read-Service

  kafka:
    admin:
      auto-create: true
    bootstrap-servers:
      - localhost:19098
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-commit-interval: 5000
      auto-offset-reset: earliest
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5435/msone_db?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  kafka:
    topic:
      employee:
        response-employee-topic: employeeWriteResponseTopic # produce to this
        group-id: employee-group
        partitions: 3
        replica: 1
